const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Ullamcorper eget nulla facilisi etiam dignissim. Est lorem ipsum dolor sit amet. `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Ut enim blandit volutpat maecenas. `,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Maecenas sed enim ut sem viverra. Faucibus vitae aliquet nec ullamcorper sit. `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `At tellus at urna condimentum mattis pellentesque. Hac habitasse platea dictumst quisque sagittis. Integer malesuada nunc vel risus commodo viverra maecenas. `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Egestas fringilla phasellus faucibus scelerisque. Gravida dictum fusce ut placerat orci. Nunc non blandit massa enim nec dui nunc mattis enim. `,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Semper quis lectus nulla at volutpat diam ut venenatis. Amet cursus sit amet dictum sit amet justo donec.  `,
  },
];
export default menu;
